services:
    server-dev:
        build:
            context: ../
            dockerfile: ./docker/dev.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - ../.env.local

    server-prd:
        build:
            context: ../
            dockerfile: ./docker/prod.Dockerfile
        ports:
            - "4000:4000"
        env_file:
            - ../.env.local
